# netlify.toml
[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "20"
# Allowlist public URL keys so secrets scanning won't fail on your domain
SECRETS_SCAN_OMIT_KEYS = "PUBLIC_SITE_URL,NEXT_PUBLIC_SITE_URL"

[context.production.environment]
NEXT_DISABLE_TURBOPACK = "1"

[[redirects]]
from = "/"
to = "/admin"
status = 301
force = true

[[headers]]
for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
package = "@netlify/plugin-nextjs"